version: '3'

services:
  turn-peer:
    entrypoint:
      - e2e
      - peer
    depends_on:
      - turn-server
    links:
      - turn-server
    build:
      context: ..
      dockerfile: e2e/Dockerfile
      args:
        CI_GO_VERSION: ${CI_GO_VERSION}
    environment:
      - CI_GO_VERSION
  turn-client:
    depends_on:
      - turn-server
      - turn-peer
    links:
      - turn-server
      - turn-peer
    build:
      context: ..
      dockerfile: e2e/Dockerfile
      args:
        CI_GO_VERSION: ${CI_GO_VERSION}
    environment:
      - CI_GO_VERSION
  turn-server:
    build:
      context: ..
      dockerfile: e2e/server.Dockerfile
      args:
        CI_GO_VERSION: ${CI_GO_VERSION}
    environment:
      - CI_GO_VERSION
